version: '3.8'

services:
  # Web Server (Nginx)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  # Flask Backend
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wis_shop
    depends_on:
      - mongodb
    networks:
      - app-network

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 