version: '3.8'

services:
  # Web Server (Nginx)
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  # Flask Backend
  flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGODB_URI}
    networks:
      - app-network

# Δίκτυο για την επικοινωνία μεταξύ των containers
networks:
  app-network:
    driver: bridge

# Τόμος για την αποθήκευση των δεδομένων MongoDB
volumes:
  mongodb_data: 