version: '3.8'

services:
  # Web Server (Nginx)
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  # Flask Backend
  flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile.flask
    environment:
      - MONGO_URI=mongodb+srv://nastosalex4:JLcrIqGKuVww93Ld@cluster0.eknhq5k.mongodb.net/pettoyshop?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 